### ISSUE TITLE
Reporting gender and ethnicity

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#100]
As stated in #21, Don would like an easier way (than, say, keeping a spreadsheet) of keeping track of applicants' answers to the (optional) question of what race and gender they are. @werebus and I were chatting about this today and came to the conclusion that since the questions and answers on the form are all user-edited it would be very difficult on our end of things to sort through them for key words. The only way to do it right now would be to scan the prompts for the key word of "race" but then "have you ever driven a race car" would show up as well, so we think this is a poor solution.

A better idea might be to make just these two questions non editable, or static. Meaning we ask Don how he wants the questions to look, and have the user fill in those fields. 

Thoughts?

**Comment by werebus** [comment]
To elaborate, slightly: EEO data should be pretty uniform across departments and positions (since it's Federally mandated).  It doesn't seem like that bad an idea to just make these bits of data attributes of the `ApplicationRecord`

**Comment by dfaulken** [comment]
True - I suppose those attributes are important regardless of the position.

**Comment by werebus** [comment]
It's worth mentioning that the numbers Don needs for his spreadsheet are actually the numbers of current employees.  He does, however need the applicant data for a "narrative" that he writes.

**Comment by dfaulken** [comment]
Interview has a `hired` attribute, so it's definitely possible to do this query within this app.

**Comment by werebus** [comment]
Sort-of, although there's a difference between "hired" and "works for us"

**Comment by dfaulken** [comment]
@Anbranin, this is done, yes?

**Comment by Anbranin** [comment]
Yeah totes

On Wed, Jan 6, 2016 at 3:02 PM, David Faulkenberry <notifications@github.com
