### ISSUE TITLE
Lingering issues from CSV export/import

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#104]
1. The file was comma-separated but some of the prompts had commas in them. The import threw out any columns after the first two, so we've lost that data (on the site, some manual editing of the CSV file could salvage this);
2. There are some character formatting weirdnesses (all apostrophes, quotation marks, etc.), and all question marks seem to have vanished?

Example:

![screen shot 2015-11-15 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/3988134/11170260/c4b8e768-8b9c-11e5-8b26-988063d0e535.png)
![screen shot 2015-11-15 at 1 28 18 pm](https://cloud.githubusercontent.com/assets/3988134/11170261/c4ba10ac-8b9c-11e5-9d6c-2db6f288311f.png)

**Comment by werebus** [comment]
On number 1: kind of late in hindsight, but ruby's [`CSV` library][1] has a `to_csv` method included into `Array` that will do the work of figuring out escaping for you to avoid that problem.

On number 2: `&#39;` *is* a single-quote, and it's stored as `&#39;` in the database for some reason, but Rails is being helpful and escaping it for you, so it comes to the browser as `&amp;#39;`

[1]:   http://ruby-doc.org/stdlib-2.0.0/libdoc/csv/rdoc/CSV.html

**Comment by dfaulken** [comment]
Thanks @werebus - it couldn't hurt to go ahead and make that change to the CSV export (since it is something people may wish to use in the future).

**Comment by enragednuke** [comment]
So is this closed? I see merged PRs that reference this but this is still open.

**Comment by werebus** [comment]
Not really, no.  The bug that caused the first half of this issue is fixed. However, this:

>  ...The import threw out any columns after the first two, so we've lost that data (on the site, some manual editing of the CSV file could salvage this)...

hasn't been addressed as far as I know.  The second half of this issue is likely a wontfix.

**Comment by enragednuke** [comment]
I'm confused, based on the page Dave edited, there seems to be only 3 columns (record id, prompt, response). I see prompt and response in the screenshot, so I assume it isn't losing any columns (I'm also assuming the record ID just isn't shown)

Do you mean rows? I see in the screenshot there's only the first two rows. It seems like a big issue not to fix.

**Comment by werebus** [comment]
So the screenshot doesn't show an example of issue 1.  Here's a quick (made-up) example though

```csv
record_id, prompt, response
1, List 3 things you like, Well, I like puppies, kittens, and flowers
```

What got imported:

record_id | prompt | response
-------------: | :--------- | :-----------
1 | List 3 things you like | Well

**Comment by enragednuke** [comment]
Ooh, I see. That seems like an issue with delimiters. It could be fixed by manually configuring the delimiter (default comma) to something else, but for the sake of consistency with CSVs we probably don't want to do this. 

There's probably also some easier solution (I doubt we're the first to encounter a predicament like this). I'll try doing some research into this today. I can think of a few things to try out.

**Comment by werebus** [comment]
Yeah,  it *is* fixed by #107, but the data in production that were initially munged by the bug remain munged.

**Comment by enragednuke** [comment]
Oh, so there's just lingering data that got chomped, but not any of the current data is getting chomped? Gotcha, thought it was still happening.

**Comment by dfaulken** [comment]
It hasn't been complained about since — I'm calling this a wontfix, and we'll endeavor to learn from our mistake.
