### ISSUE TITLE
Confgurable reply_to on ApplicationTemplate

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#115]
Same reason as https://github.com/umts/ft-forms/issues/39.

Also I think we should come up with a better application denial email closing text than

> Best,
UMass Transit

**Comment by enragednuke** [comment]
![screen shot 2016-04-04 at 1 36 03 pm](https://cloud.githubusercontent.com/assets/9220151/14257117/33165f9c-fa6a-11e5-8cf1-be35d0fd93c9.png)

wat

**Comment by dfaulken** [comment]
lol
