### ISSUE TITLE
Recruitment trends by graduation year

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#116]
in #21, @sherson mentioned a desire for "Number of applicants, grouped by year of graduation (recruitment trends)"

I assume that Adam is the best person to ask about how this reporting should be organized.

**Comment by Anbranin** [comment]
This leads us to the same issues that reporting ethnicity and gender had. We would need to make a static question that isn't an editable part of the form.

**Comment by sherson** [comment]
Don said he only needs this for current employees, so never mind.
