### ISSUE TITLE
Refactor ApplicationRecord from a B on Code Climate

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#118]
https://codeclimate.com/github/umts/jobapps/ApplicationRecord

**Comment by dfaulken** [comment]
Specifically it's complaining about "complex code in `ApplicationRecord` definition outside of methods."

There is a lot here, but it's the functional unit of the site. Potential refactor target, but it may simply be a complex object and there's not a lot we can do to pare it down.

Does anyone have thoughts?

**Comment by werebus** [comment]
I think it's probably fine.  I had a few thoughts that are all pretty half-baked:

1.  Taking some scopes and making them full-on methods alleviates the "outside of methods" complaint but doesn't really decrease the complexity from the perspective of a code-reader.
2.  A [few][1] of those scopes seem somewhat generic and could be extracted, but is a "generic" scope that's only used by one model really "generic"?

Not too relevant in this case, but excellent read that I found looking into this: "[7 Patterns to Refactor Fat ActiveRecord Models][2]"

[1]:  https://github.com/umts/jobapps/blob/9a940dea611cce9dc47cedfcc7fc64434640073d/app/models/application_record.rb#L19-L21
[2]:  http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/

**Comment by dfaulken** [comment]
![screen shot 2015-12-22 at 4 20 32 pm](https://cloud.githubusercontent.com/assets/3988134/11966158/f4246408-a8c7-11e5-8e2e-664f2922a817.png)
