### ISSUE TITLE
Modify headings and expanations on show page

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#119]
Don:

>  Good Morning,

>  The online application seems to have had an issue overnight. The Job Requirements portion has gone Bold.

---

@sherson

>  I talked to Don... everything is mostly fine. 

>  What he's referring to is that all prompts and responses appear when viewing recent applications ~~(that were submitted since the last code commits)~~. 

>  ~~When viewing old applications, the text for headings, explanations, and one of the yes/no fields aren't rendered (the rest of the yes/no fields render).~~

>  The change is especially noticeable since the "Minimum Job Requirement..." text is long (and that column is bold). It's a tad ugly rendered as a wall instead of a list, but the new behavior is what I'd expect.

---

@sherson:

>  Never mind what I wrote about a yes/no field not appearing. I just misread the page (only the headings and explanations weren't showing).

>  Anyway, it's all set.

**Comment by werebus** [comment]
After all that, it turns out there is still a request from Don

Headings and, especially, explanations show up as regular fields in the `ApplicationRecord#show` view, and a wall of unformatted text is a little rough especially on a printout.

Proposed fix:

*  Span both columns with those field types
*  Don't make them bold
*  Run the explanations through the markdown parser (eg [here](https://github.com/umts/jobapps/blob/master/app/views/application_drafts/show.haml#L26)).

**Comment by werebus** [comment]
I still think it's worthwhile to parse the explanation markdown, though.

**Comment by dfaulken** [comment]
Agreed - I missed that that wasn't in #123.

**Comment by Anbranin** [comment]
Sorry, this is not quite ready.
