### ISSUE TITLE
Reminder about EEO questions on drafts

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#120]
Having removed the duplicate EEO questions from the bus application, it occurred to me that someone looking at a draft of the application might think that they were missing entirely.

Perhaps a reminder box of some sort that says something about how people will also be asked the EEO questions?

**Comment by Anbranin** [comment]
Easy enough to just put something on the bottom, yes.

**Comment by bgregg** [comment]
This issue fixed by PR #212. Can be closed

**Comment by werebus** [comment]
Agreed
