### ISSUE TITLE
Exports / reports by position

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#126]
At the moment all of the exports and reports on the dashboard don't discriminate by department.  Probably they should be filterable or something.

**Comment by Anbranin** [comment]
I added a plugin for stuff and now the dashboard looks like this. Before I go any further, what do you all think??
The plugin is called SumoSelect.

![screen shot 2015-12-30 at 4 04 59 pm](https://cloud.githubusercontent.com/assets/9645316/12057470/5c65bf2e-af0f-11e5-9e5c-3d539c9b0c6c.png)
