### ISSUE TITLE
Replace most view tests with integration tests

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#128]
A lot of what we do in our view tests is making sure forms have certain elements, or certain buttons or links exist. Also, a good chunk of what we do in our controller tests is making sure the controller returns certain view-feeding flash variables when a form is or isn't submitted properly.

It seems like some of these goals might be met more easily, more fluently and more thoroughly with integration tests à la Capybara, for instance - particularly since our app isn't that dependent on javascript.

Does anyone have thoughts about this?

**Comment by dfaulken** [comment]
Having not received any objections, I'm going to move forward with this.

**Comment by dfaulken** [comment]
@akaplo and @bgregg will be pair-programming this.

**Comment by akaplo** [comment]
FYI I haven't forgotten about this :stuck_out_tongue_closed_eyes:

**Comment by dfaulken** [comment]
Hey @akaplo, @Anbranin has been working on integration tests as part of an issue she's working on - it'd be great if you and @bgregg would look over her PR once that's up. It'll address a good portion of this issue.
