### ISSUE TITLE
Adding new position behavior

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#134]
Today, I added a new department and position. Under my new department (Special Transportation, I called it) I clicked the "add new position" button. It brought me to the positions/new page, where it turns out there is a dropdown box to select the department. Since dropdowns are alphabetical, the one it automatically had on top was "Our Department". It seems to me that it clicking the "add new position" button underneath the department button should lead you to a page to create a position for that department. Or, we should put the "add new position" button somewhere else entirely, and not have a link under every department to create a position.
I can just see someone IRL doing this and accidentally creating a position for Bus when they meant to do one for ST, since each department has a link in the dashboard underneath it to create a position.
Thoughts?

**Comment by dfaulken** [comment]
Agreed.
