### ISSUE TITLE
Subsidiary accounts can log in

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#136]
Just accidentally logged into the site as @sherson with the "rtic" account.  It's not a major issue, but it does mean that the TRSpvs can log in as Don pretty easily since they both have access to an account that's "Don's"

In round-three we guard against this by checking whether 
```ruby
request.env["UMAPrimaryAccount"] == request.env["uid"]
```

See umts/round-three#29

**Comment by dfaulken** [comment]
We discussed briefly today whether, for a more public-facing app, it'd be worth writing a specific error message or page for when this occurs. Thought @sherson might have input.

**Comment by sherson** [comment]
Sure, a "polite" page when someone attempts to log in with a *role subsidiary* account seems like a good idea. 

If you're looking for suggestions for text, perhaps something like:

> Role subsidiary accounts can not be used to access this site. Please login with your primary NetID. If you need assistance, contact transit-it@admin.umass.edu.

**Comment by AkivaGreen** [comment]
I can work on this.
