### ISSUE TITLE
Site Contact link in footer broken

### ISSUE THREAD

**Issue by sherson** [umts/jobapps#138]
Goes to https://transit-jobapps.admin.umass.edu/dashboard/transit-it@admin.umass.edu

(noticed while commenting on #136)

**Comment by werebus** [comment]
Sort of.  The link is actually like so:

```html
<a href="transit-it@admin.umass.edu">Site Contact</a>
```

And your browser is just trying to do the best it can with that. Without a protocol or leading `/`, that can only technically be a relative path.

For reference:

http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-mail_to
