### ISSUE TITLE
Fix "mass_assign_permit!" issue in app/controllers/application_drafts_controller.rb

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#146]
Parameters should be whitelisted for mass assignment

https://codeclimate.com/github/umts/jobapps/app/controllers/application_drafts_controller.rb#issue_569555c5fcebfa000162b1c8

**Comment by dfaulken** [comment]
In looking at this one, I'm confused as to whether drafts accept *any* parameters other than `questions_attributes`.

@Anbranin, do you know of anything other than attributes of questions which can be edited at `ApplicationDraftsController#edit`? Is there anything else this controller method should allow to be edited?

**Comment by Anbranin** [comment]
Currently, questions and the attributes thereof is the only thing people can edit about drafts. Perhaps in the future one might wish to edit the name of an application, but that's an enhancement for later.

**Comment by dfaulken** [comment]
Great, thanks!
