### ISSUE TITLE
Consistent button styling

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#156]
In `ApplicationDraftsController#edit`, it'd be nice if this button:

![screen shot 2016-01-12 at 3 21 32 pm](https://cloud.githubusercontent.com/assets/3988134/12275842/519d5b3e-b940-11e5-84f1-3a3d0510c422.png)

looked like these buttons:

![screen shot 2016-01-12 at 3 21 40 pm](https://cloud.githubusercontent.com/assets/3988134/12275846/55b60806-b940-11e5-8c14-a0bf902e1fae.png)

We should probably do a general sweep for consistent form element styling while we're at it.

**Comment by bgregg** [comment]
I'll get working on this one. Shouldn't be too bad. If someone could assign me that'd be cool.
