### ISSUE TITLE
Students shouldn't re-submit applications?

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#17]
Once you've submitted an application for a position, you shouldn't be allowed to submit another until your first application is reviewed, right?

Pros:

+ no spamming staff with multiple applications

Cons:

+ students will be able to 'see' if their application's been rejected by looking at whether or not they're able to submit a new one.

**Comment by dfaulken** [comment]
@sherson said that that sounds fine.

**Comment by sherson** [comment]
:+1: 

I actually don't see that as a con. Ideally they'd see a link to review their application status (in place of the link to submit). Whether or not they click the link is up to them.
