### ISSUE TITLE
Exception on past applications when no departments are selected

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#183]
```
An ActionController::ParameterMissing occurred in application_records#past_applications:

  param is missing or the value is empty: department_ids
  app/controllers/application_records_controller.rb:45:in `past_applications'
```

Happens on past applications, but probably also on the other reports as well.  If the field is required, we should enforce that before the form gets submitted.

**Comment by werebus** [comment]
Also, I notice that all three department selectors have an `id` of `department_ids` which could cause a problem later.

**Comment by Anbranin** [comment]
Trying to work on this, but encountering issues. This is what it looks like:
![screen shot 2016-01-25 at 1 14 38 pm](https://cloud.githubusercontent.com/assets/9645316/12559879/9cd80976-c365-11e5-85e2-fa7c7f225e94.png)
But the required: true bit isn't doing anything. Like, when I press the "list applications" button, nooothing happens. Required: true works for the text_field_tags, why not this?

**Comment by dfaulken** [comment]
Let's move this over to slack.

**Comment by werebus** [comment]
When you say, "nothing happens," do you mean that the page doesn't submit?  If so, my guess is that it *is* working.

My guess is that SumoSelect has some CSS that obscures the validation messages in some way.
