### ISSUE TITLE
Fix "we're not hiring right now" text

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#188]
This is a little awkward:

<img width="573" alt="screen shot 2016-01-31 at 11 02 26 pm" src="https://cloud.githubusercontent.com/assets/3988134/12708567/c1a88024-c86e-11e5-8c0f-632c3a908bfc.png">

**Comment by Anbranin** [comment]
I know. We talked about this a lot. What would be pretty cool is a configurable text, amirite?

**Comment by Anbranin** [comment]
Alternatively, "We are not hiring {#/@position}" + 's' ' right now. Please check back.' That should work in most cases, but I can see how it may not.

**Comment by dfaulken** [comment]
Configurable is the way to go here. Just like @enragednuke is routing application templates by department name and then position name, I think a similar layout of the config in the `application.yml` file would be cool, so that people could configure the messages like:

```yml
deactivated_application:
  Bus:
    Operator: "We are not currently hiring bus drivers."
```

which you could then invoke using `ConfigurableMessages` as

```ruby
configured_value([:deactivated_application, department.name, position.name], default: 'some default')
```

where `department` and `position` are the objects that an application belongs to.
