### ISSUE TITLE
Correct EEO spelling

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#191]
This should be "ensure":

<img width="775" alt="screen shot 2016-02-01 at 12 20 58 am" src="https://cloud.githubusercontent.com/assets/3988134/12709402/bc1b4c76-c879-11e5-8f45-7909f77307c6.png">

**Comment by sherson** [comment]
It's spelled correctly (ensure) when a staff person [views a draft](https://github.com/umts/jobapps/blob/master/app/views/application_drafts/show.haml#L82) of an application, but it's spelled incorrect (insure) on [applications](https://github.com/umts/jobapps/blob/master/app/views/application_templates/show.haml#L151).
