### ISSUE TITLE
Use expect_flash_message for integration tests

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#192]
Completely forgot about this helper method - it's nice not only to make sure that a method is there, but that it's being taken from the YML file.

**Comment by akaplo** [comment]
I'm interested in taking this on.  I've changed all of the tests that render positive flash messages (using ```show_message```) to use ```expect_flash_message```, but I'm having trouble with ones that render error messages.

Rendering error messages is done by calling ```show_errors(object)``` from the ApplicationController, which creates a ```flash[:errors]``` object that is then used.  ```expect_flash_messages``` doesn't ever check that this is called; it only cares about ```show_message```.  So, I think this is why I get console errors when I use it to check for error messages.  

If I'm right, should I update ```expect_flash_message``` to take into consideration that an error flash may be rendered, or should I just leave it and forget about updating the integration tests in those spots?  The issue I think we'd run into with updating it is that show_message takes a key (symbolized name of the message) and a hash (which we are doing as, for example, ```default: "This is a message"```), whereas ```show_errors``` simply takes an object (which we're passing as the object that we just failed to create/update/etc). 

If I were to update it, I'd guess that we need to change the ```receive``` matcher to be fine with ```:show_message``` or ```show_errors```, ie:
```ruby
  expect_any_instance_of(ConfigurableMessages)
    .to receive(:show_message || :show_errors)
end
```
(which doesn't work...I tried).  I tried looking for a ```.or``` matcher or the like (which would enable me to write something to the effect of ```.to receive(:show_message).or(:show_errors)```) but came up dry.

**Comment by dfaulken** [comment]
`show_errors` is a private method on ApplicationController. It doesn't have to do with configurable messages, so it's outside the scope of this issue. You don't need to worry about it.

**Comment by dfaulken** [comment]
That said, it would be

```ruby
expect_any_instance_of(ApplicationController)
  .to receive(:show_errors)
```

**Comment by akaplo** [comment]
Ok.  Then where are the error messages coming from?  An example of a passing test:
```ruby
it 'has flash errors' do
      click_on 'Save changes'
      expect(page).to have_selector '#errors', text: "First name can't be blank"
    end
``` 
certainly seems to render a configurable error message, and the controller code that corresponds
```ruby
def create
    @user = User.new user_parameters
    if @user.save
      show_message :user_create,
                   default: 'User has been created.'
      redirect_to staff_dashboard_path
    else show_errors @user                               <---this line
    end
  end
```
calls some sort of show_error function. Am I just confusing it with a different function?

**Comment by dfaulken** [comment]
Let's move this to Slack.

**Comment by akaplo** [comment]
Okey doke.
