### ISSUE TITLE
Phone number auto-fomatting?

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#204]
Couldn't help but notice that Don added to the phone number fields, e.g.:

<img width="639" alt="screen shot 2016-02-07 at 9 13 10 pm" src="https://cloud.githubusercontent.com/assets/3988134/12877329/b2f22438-cddf-11e5-9f7f-c861038fff38.png">

Perhaps we can help (with Javascript)?

**Comment by bgregg** [comment]
I can look into this one. I need some JS practice

**Comment by dfaulken** [comment]
I have a series of three related issues on round-three that are higher priority.

**Comment by bgregg** [comment]
okay sounds good!
