### ISSUE TITLE
Application denial email doesn't reference the position

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#224]
This will pretty much be ameliorated by #115, but I noticed that when someone gets denied and they reply to the email, it's not 100% clear what position they were denied for.

**Comment by bgregg** [comment]
Fixed by PR #239. Can be closed.

**Comment by werebus** [comment]
Can you point out where the fix is?

**Comment by bgregg** [comment]
Now that I look at it, it actually fixed a separate non GitHub issue, but never addresses this one
