### ISSUE TITLE
Images not displaying on live site

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#236]
Specifically, the calendar images:
![screen shot 2016-04-21 at 5 20 28 pm](https://cloud.githubusercontent.com/assets/9645316/14724650/82dd7730-07e5-11e6-86fb-593b9fe6a6a4.png)

**Comment by werebus** [comment]
Ah, the dreaded asset fingerprinting.  In production, the calendar icon isn't `calendar.gif`, it's `calendar-ba53f7db11b3d9bb2e114873772432e357058321154e9c095472fcd953a97cc7.gif` at the moment, but that could change.

A quick google search suggests that the solution is to make `datepicker.js.coffee` into `datepicker.js.coffee.erb` and specify a url like this:

```
buttonImage: "<%= asset_path 'calendar.gif' %>"
```

**Comment by Anbranin** [comment]
K I'll get around to it at some point.
