### ISSUE TITLE
Last question is saved to the database with no attributes

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#246]
Questions are validated for data_type, number, prompt -- and the last question of every application record (which is a new question, there so people can edit the application) has no attributes and is still somehow being saved to the database.
HOW.

**Comment by Anbranin** [comment]
https://github.com/umts/jobapps/commit/031c985094005d6015ade70252d8056265712eb8#diff-3bdf57cad0d15d5a677b3ffa0e850839R27

**Comment by dfaulken** [comment]
We should step through with a debugger to sort out how this is happening.

**Comment by Anbranin** [comment]
That's my favorite thing! YES.
