### ISSUE TITLE
Track down bootstrap CSS authors

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#251]
Some of the bootstrap-related CSS strikes me stylistically that it may have been written by someone not at this organization. If this is the case, it'd be nice to track down the original sources and attribute their work to them.

**Comment by akaplo** [comment]
@dfaulken can you give an example?

**Comment by dfaulken** [comment]
[Here](https://github.com/umts/jobapps/blob/master/app/assets/stylesheets/dashboard.scss#L1-L5) are the specific lines what prompted me to open this issue.

https://github.com/umts/jobapps/pull/250/files#r65746495

**Comment by akaplo** [comment]
Ah. Git blame informs us that @enragednuke added this code with the commit message of "sass magic," a message that I wholeheartedly agree with 🙃

**Comment by enragednuke** [comment]
I wrote that myself. I just had to google how SASS syntax worked. It's just a `for` loop, nothing special.

**Comment by enragednuke** [comment]
I also would like to know how `strikes me stylistically` applies to standard syntax?

**Comment by dfaulken** [comment]
Not sure, it was months ago. We can close this.

**Comment by enragednuke** [comment]
oh I didn't even notice this issue was just a graveyard issue from the summer that got revived lol

**Comment by akaplo** [comment]
I get what he meant; the syntax being used was so out-of-place compared to all the other styles that we wrote.

**Comment by enragednuke** [comment]
Me coder me write only best code (╯°□°)╯︵ ┻━┻ 🐒
