### ISSUE TITLE
PDF of Application Record doesn't look pretty enough

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#260]
The Training Supervisor, who prints these application records, recently began having issues printing directly from the website. The PDF we gave him (with a 'print this page' button) was not pretty enough (his words), and printing the web page directly gave him a black sheet. What a waste of ink. I thought, then, that I would make the PDF better looking for him. These are the specific things he requested:

The explanation can not be displayed, that's fine
There should be padding between sentences, and padding horizontal, and vertical--basically everything needs to be more spacious.
Horizontal lines separating question/answer pairs
A box around the whole thing. Makes it nice and enclosed.
The email address of the applicant needs to be included in the header along with their name and the date they applied
Try removing the shading, maybe it'll be nicer without it

Update: He just told me he's now selecting 'save as PDF'  and the application record is printing EXACTLY like he wants, which is how it looks on the application_record/show page. Why even bother making a PDF, then?

I'd mark this 'low priority' if it was an available label.

**Comment by werebus** [comment]
([Ahem][1]). Still worth looking at even if a particular user has found some sort of workaround involving copying-and-pasting into Excel, saving as a Word document, printing that to a PDF, printing from Adobe Pro...

That is...the fact that someone needed to find some sort of janky arcane workaround is an indicator that we're not writing the software they need.

[1]:  https://github.com/umts/jobapps/labels

**Comment by Anbranin** [comment]
👍  okay. Not time sensitive still but will do.

**Comment by dfaulken** [comment]
This is a time when it's nice to keep in mind that Donald Chapman isn't our only intended user.

**Comment by Anbranin** [comment]
You guys I'm so good at making PDFs now.
I asked @sherson and @werebus about the size of the information in the header, they are both of different opinions. However, Donald Chapman says he likes it. I asked him if he'd stop printing the web page now and he said "probably" which is about as good as I'm gonna get I guess.

![screen shot 2016-07-18 at 12 55 28 pm](https://cloud.githubusercontent.com/assets/9645316/16923192/0ddb4fce-4ce7-11e6-9b28-95fe992d360d.png)
