### ISSUE TITLE
Desired SPIRE value unclear when creating user

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#266]
In the users/new form, (used by admins to create a new staff user), the SPIRE field should be /spire_number@umass.edu, not merely the number. However, the admin creating a user yesterday did not know this and merely entered the number, and the new staff user could not log in until I changed his spire ID in the database to have an /@umass.edu after. Could we somehow make it clear that the number should be entered with a /@umass.edu after it? Perhaps a placeholder?

**Comment by werebus** [comment]
Placeholder should be fine.

For internal umts-only applications, I think we can handle the appending of `@umass.edu` in the controller, but I think storing  `@umass.edu` in the database is the right way to go for the same reason UMass does it (something, something, federated auth...).

By the way, Shibboleth's name for this field is [`fcIdNumber`](https://github.com/umts/jobapps/blob/master/app/controllers/application_controller.rb#L58).

**Comment by werebus** [comment]
```xml
<Attribute name="urn:oid:1.3.6.1.4.1.36146.1.1.1" id="fcIdNumber"/>
```

**Comment by dfaulken** [comment]
We've also done validations on our other apps - no reason not to do that here as well.
