### ISSUE TITLE
Applications that happened today don't show up when searching with an end date of today

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#267]
An application was submitted last night at 8:49 pm, which in UTC time is this morning at 1:49 am. Don searched for applications from a week ago until today, which seems to have not included that application.

Workaround was to search with an end date of tomorrow.

**Comment by Anbranin** [comment]
I think this happens no matter when they are saved. I suspect the 'between' scope to be the problem. If a record is submitted on the 7th at any time, one must have an end-date on the 8th for it to show up in past applications.
