### ISSUE TITLE
PDF doesn't display unavailability

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#269]
We need to do more with Prawn and make it actually render the unavailability so the Training Supervisors can print out people's unavailability. Right now, applicants are filling it out twice.

**Comment by Anbranin** [comment]
Correction: It does, Don just probably hasn't turned on the feature yet.

**Comment by dfaulken** [comment]
Does he know how to?

**Comment by Anbranin** [comment]
I messaged him on FB telling him I'd show him tomorrow, if he reminded me.

**Comment by Anbranin** [comment]
Don showed me this morning that the unavailability is indeed not showing up on the PDF. I seen it with my own two 👀

**Comment by Anbranin** [comment]
It's not happening in development.. only production. OMG.

**Comment by bgregg** [comment]
It's working on master in development, not sure what could have happened between there

**Comment by bgregg** [comment]
thats no bueno

**Comment by bgregg** [comment]
DId it get deployed properly? I believe @dfaulken was the one who deployed it because I can't deploy Rails 4 apps yet

**Comment by Anbranin** [comment]
You know what, Brian? I realized this like 1 minute before you commented, you win the prize--it hadn't been deployed. I just compared the code on production to development and noticed a striking difference. All set now!
