### ISSUE TITLE
Alert Staff That a Saved Application Has Come Back

### ISSUE THREAD

**Issue by akaplo** [umts/jobapps#271]
First thought of in #270.  When we save an Application for a Position for later, it may be useful to email the staff user tied to that Position when the application has been auto-removed from the "saved for later" list and brought back into the Dashboard.  This could be useful for staff users who don't check their dashboard every day so that they can review an application in a timely manner.

**Comment by Anbranin** [comment]
Sounds like a great idea. This should be configurable per Position.

**Comment by AkivaGreen** [comment]
I can work on this.

**Comment by dfaulken** [comment]
#279
