### ISSUE TITLE
Do away with reply-to email

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#273]
I thought this was already an issue, but I can't find it anywhere.

Since gmail removes the 'reply-to' attribute we set, we should instead add a line in any relevant emails stating that one should not reply to this address, but instead direct questions to application_template.email--and whether that displays should be configurable. Not sure what exactly this should look like, I'm going to tinker with it a bit.

**Comment by werebus** [comment]
>  gmail removes the 'reply-to' attribute we set

Are you sure about this? Any Google searches to this effect don't turn up anyone else having this problem. And they certainly still allow you to *use* the feature in GMail:

![screenshot_2016-11-14_16-20-43](https://cloud.githubusercontent.com/assets/240275/20283294/689ce06a-aa86-11e6-9ba5-3691fc5da7fc.png)

Perhaps we're doing it wrong in some way?

**Comment by werebus** [comment]
I don't think anyone has actually ever used the reply-to feature:

```ruby
ApplicationTemplate.where("email != ''").count
#=> 0
```

**Comment by Anbranin** [comment]
I watched over Don's shoulder while we looked at his application_template together, and I saw a reply-to address. Something is not right.

**Comment by dfaulken** [comment]
Perhaps you were looking at a draft? @werebus's query still returns 0.

**Comment by werebus** [comment]
Nope

```ruby
ApplicationTemplate.find_by_slug('bus-operator').drafts.map(&:email)
#=> [nil, nil, nil, nil, nil]
```

This is, perhaps, a silly question.  Is there any chance Don was looking at the top of the page where it shows the current user *their* name and email address?

![screenshot_2016-12-06_08-43-44](https://cloud.githubusercontent.com/assets/240275/20927538/2183cc00-bb90-11e6-9dd2-4433368d8807.png)
