### ISSUE TITLE
Give application_drafts the same attributes as their respective template

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#277]
Change Template#create_draft to give the drafts all the attributes of their template except the id or whatever

**Comment by dfaulken** [comment]
What was the reason we opened this?

`ApplicationTemplate.column_names - ApplicationDraft.column_names` gives me the columns:

+ position ID
+ active
+ slug
+ EEO enabled?
+ Unavailability enabled?

Which of those ApplicationTemplate attributes also need(s) to exist on ApplicationDraft?

**Comment by werebus** [comment]
Something to do with #276?

Both models *have* and email field, but every time you created a drafit it was being initialized to `''`  @Anbranin fixed that problem, but I think this issue is referencing [this comment](https://github.com/umts/jobapps/pull/276#issuecomment-265229114)

**Comment by dfaulken** [comment]
Ah, so by 'give the same attributes' we mean the data, not the columns themselves?

**Comment by werebus** [comment]
:+1: pretty sure, yes.
