### ISSUE TITLE
Interface does not have a way to make a current user into staff

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#285]
If someone has a User object (say, me) in the database who is not staff, there is no current way to make them into staff using the website, you must go into the console. Trying to "create a new staff member" only leads to an invalidation of uniqueness on spire id.

**Comment by AkivaGreen** [comment]
Are you sure is current user or an administrator?

**Comment by Anbranin** [comment]
Basically the interface to make someone a staff member sol should first try
to find an existing user and change their staff or admin or whatever
attribute to true (whatever the create action does). If it can't find one
only then should it do the create action that it currently does.

**Comment by AkivaGreen** [comment]
My bad this was a comment pertaining to round-three still. I forgot to just lineout the comment. My apologies. Thank you.

**Comment by dfaulken** [comment]
Good point! This is almost due to become evident another way; that is, it's almost time for users who were hired through the system to start being promoted to the staff positions where they'll need to administrate the system. This would've become evident then, too.
