### ISSUE TITLE
Configurable email for application rejection

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#290]
Instead of having the emailing the applicant about a rejected application be configurable in the YML file, we should make it configurable on the client side. 
During brainstorming with @dfaulken we came up with the idea to, along with having a checkbox for "email applicant reason for rejection?" to be able to set the default checked or not. Like, have a users_position join model and have it have a boolean attribute that defines whether or not that checkbox is checked by default.

**Comment by Anbranin** [comment]
Pretty sure this is implemented already

**Comment by werebus** [comment]
Well, it's certainly not implemented as described above. That is, I don't see anywhere on the app where I can set the default state of the "email applicant" checkbox.

**Comment by Anbranin** [comment]
Whoops yeah. What was actually implemented was a per-person "email the applicant" checkbox that is not checked by default. This meets the current expectations of the users.
So right now if someone wanted the default to change they'd have to ask IT, but since that's extremely easy I don't see a reason to change it. If you think it should be worked on, I won't die on this hill.
