### ISSUE TITLE
Saved applications not moving back to dashboard on date

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#292]
There's a [cron job](https://github.com/umts/jobapps/blob/master/config/schedule.rb#L1-L3) that's supposed to move the application back to the dashboard but something along the way is failing and those application records are just not moving back.

**Comment by dfaulken** [comment]
Have we checked everything's all set on the server administration end? (That is, is this a code problem?)

**Comment by dfaulken** [comment]
⚡️ @Anbranin, never got an answer to my above question

**Comment by werebus** [comment]
@Anbranin found this:  d2a7412e8f6df2261836bdbef4994dfbe8488ec1, but I'm not sure that's the only issue. Is it working now?

**Comment by Anbranin** [comment]
Apparently that was NOT the only issue. I pushed that code and thought "that's probably it no more worries" but the application I had saved-for-later is not getting moved back. I don't really know what to do, guess I'll do some research tomorrow.

**Comment by Anbranin** [comment]
The cron job is getting run on one of the releases... not the current deployed version.

**Comment by Anbranin** [comment]
I think I got it. The part of the task I think is wrong in cron syntax looks like this:
`cd /srv/jobapps/releases/20170607195307`
From the (readme)[https://github.com/javan/whenever]:
> If a `:path` is not set it will default to the directory in which whenever was executed
No bueno! I will manually set the path.

**Comment by Anbranin** [comment]
Also this thing
https://github.com/javan/whenever/blob/c7675c81d34131f7107b2930c207c9b994895a08/lib/whenever/capistrano/v2/recipes.rb
this is doing some things. I am not sure what things but it looks like it's expecting our server setup to be different than it is.

**Comment by Anbranin** [comment]
I set the `:path` manually. Checking to make sure Capfile and deploy.rb are correct. Is it cool that it assumes that the role of our server is :db? Double-checking.

**Comment by Anbranin** [comment]
Then again, `crontab -l` on the server only lists commands related to screaming dinosaur. So, maybe Capistrano isn't updating the crontab. :)

**Comment by Anbranin** [comment]
I think that's it. If the cronjob for screaming dinosaur does in fact work, then my previous thought was incorrect (maybe I don't really know how releases work). 
@dfaulken how did you update the crontab on the server for screaming dinosaur? Capistrano is _supposed_ to do it if you add the appropriate lines to deploy.rb but in screaming dinosaur there is nothing relating to whenever in there.

**Comment by Anbranin** [comment]
P.S. I updated the crontab on the server manually and now my cron job is in there. We'll see if it works by tomorrow morning.

**Comment by dfaulken** [comment]
You don't need to add anything to the deploy config unless you want to customize the defaults. [The README](https://github.com/javan/whenever) specifies *how* to do that, but you don't need to.

**Comment by werebus** [comment]
>  The cron job is getting run on one of the releases... not the current deployed version.

What makes you think that? Are your *certain* that the release in question isn't the current release

>  `cd /srv/jobapps/releases/20170607195307`
>  
>  From the readme:
>  
>   If a :path is not set it will default to the directory in which whenever was executed
>  
>   No bueno! I will manually set the path.

Um, that  looks fine to me. You can definitely run that command from that directory.

>  Also I found this, this might explain why the :path is set to the latest release. 

That link is for an ancient version of Capistrano.  Only round-three runs on v2, I don't think that is relevant.

>  I set the :path manually. Checking to make sure Capfile and deploy.rb are correct.

It would be good to know what you meant by "set the `:path` manually."

>  Is it cool that it assumes that the role of our server is :db? Double-checking.

I don't think that's right.  Our `production.rb` says:

``ruby
server 'af-transit-app3.admin.umass.edu',
       roles: %w(app db web),
       user: remote_user
```

That is, that server serves all three roles.

>  Then again, `crontab -l` on the server only lists commands related to screaming dinosaur. So, maybe Capistrano isn't updating the crontab. :)

Just making sure, you *have to* run that command with `sudo`.  If you don't, you'll get **your user's** personal crontab (which **should** be empty).

If it's not empty, that's an indication that some app (screaming-dinosaur?) is missing [this fix](https://github.com/umts/jobapps/commit/1a0b0aa701019d98b3d8b090d185c85a498a740d).

Finally, with regard to a conversation on Slack, we *do* use identifiers. By default, Capistrano uses `set :whenever_identifier, ->{ fetch :application }`, which should be fine.

**Comment by werebus** [comment]
Whoops.  Broke it again.

**Comment by werebus** [comment]
Initially, I thought that this might be because I moved ruby again.  But it's not.  This time it's a missing `SECRET_KEY_BASE`:

```
 /bin/bash -l -c 'cd /srv/jobapps/releases/20200225170934 && bundle exec bin/rails runner -e production '\''ApplicationSubmission.move_to_dashboard'\'''
bundler: failed to load command: bin/rails (bin/rails)
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
```

**Comment by Anbranin** [comment]
Is this fixed now??? I feel like it is?

**Comment by werebus** [comment]
Turns out: nope
