### ISSUE TITLE
Applicants are not being emailed the interview date/time / approval

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#307]
Don reported this as an issue because he asked a few people if they'd gotten emails confirming the date/time of an interview and the "you're hired" email, and they said they hadn't.
This remains unconfirmed as an issue--it could be that the people he asked had just forgotten. I have not had time to look into it, so that is step one. Will update the issue accordingly when confirmed or not.

**Comment by werebus** [comment]
⚡️ Don says this is (may be?) still a problem.

**Comment by werebus** [comment]
Closed by #359
