### ISSUE TITLE
Way to "unreject" applications

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#308]
Sometimes the hiring manager rejects an application by accident. This is rare. What's less rare is that he or she will reject an application and later the applicant will email him with updated information that makes it possible to interview them (their schedules change etc). In either case, the hiring manager would like to be able to "unreject" an application (move it back to pending).

**Comment by werebus** [comment]
:zap: Requested again

**Comment by Anbranin** [comment]
Should actually get done now.

**Comment by Anbranin** [comment]
We need a "move back to dashboard" button, requested again.
⚡️
