### ISSUE TITLE
"Did you mean umass.edu?" popup

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#311]
We've had a few instances of people entering their email domain as umass.com. I suggested to Don that we might write a popup that says "did you mean umass.edu?" when someone types umass.com. He liked this idea.

**Comment by werebus** [comment]
I mean, sure, I guess.

Just to clarify, though, this only happened once.  Both errors we got were the same applicant.

**Comment by Anbranin** [comment]
This hasn't happened in two years, and umass.com _is_ a valid domain name. Unless there are objections I'm just gonna close this.
