### ISSUE TITLE
500 with invalid email

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#320]
```
A Net::SMTPFatalError occurred in application_submissions#review:

  550 5.1.1 <10/6/1999>: Recipient address rejected: User unknown in local recipient table

  app/models/application_submission.rb:76:in `deny_with'
```

Generally email failures take a while to get back to us, but in cases of the email address, "`10/6/1999`" it bounces immediately. 3 possibilities, of which we could implement any combination:

1.  Rescue the exception, provide feedback to the staff member. That said, I don't know that we provide any way to fix this particular problem.
2.  Validate email address a bit. I know [validating email addresses is a nightmare](https://www.regular-expressions.info/email.html), but... even just checking for an `@` would have caught this one.
3.  Send emails as background jobs. A lot of work (so probably not worth it except as a learning experience), but a arguably "good idea" for an action that can timeout or fail in a longish amount of time.

**Comment by dfaulken** [comment]
Don't HTML5 email fields have some amount of built-in validation?

**Comment by werebus** [comment]
It's browser-specific behavior, but yes, at least Firefox and Chromium on my laptop stop me from submitting an email field that isn't an email. That's a very cheap fix.

https://output.jsbin.com/vacafeteki
