### ISSUE TITLE
Don't email if reason-for-rejection is blank

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#326]
Requested by head of Training Department

**Comment by werebus** [comment]
Duplicate (or perhaps subset) of #290?

**Comment by Anbranin** [comment]
I think you're right that it's important to note here my reason for making it a separate issue: This was specifically asked for (the other one was my idea) and will take approximately 5 minutes to complete and maybe another 15 to update the tests. 
The other issue is the desirable end-state but will take significantly longer. If I had my druthers, I'd have this done within the week and take some time finishing the other.

**Comment by Anbranin** [comment]
That being said, closing 290 would indeed close this issue as well... I just don't believe anyone will have the time soon.
