### ISSUE TITLE
Remove "site texts" feature

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#356]
No one has ever used it, and if someone does want to request a feature they are more likely to use other interfaces.
It was a nice thought, but it's technical debt and you know how I feel about that.

**Comment by werebus** [comment]
Agreed.  We _do_ still want some sort of [Markdown tutorial](https://github.com/umts/jobapps/blob/e5c2b2b9e0d027b20e47421895b8062dc147582f/db/seeds.rb#L120-L131) somewhere (since MD is used in question rendering). But that can definitely be a static view of some sort.

**Comment by werebus** [comment]
There are exactly two `SiteText`s in the production database. They are both also defined [in the seed data](https://github.com/umts/jobapps/blob/7d36cc8b606f3b6c54688566f678e0a0722e8886/db/seeds.rb#L119-L131).

* The "`welcome`" is used [here](https://github.com/umts/jobapps/blob/7d36cc8b606f3b6c54688566f678e0a0722e8886/app/views/dashboard/student.haml#L2); it can be replaced with a `String`.
* The "`markdown explanation`" is linked to from [here](https://github.com/umts/jobapps/blob/7d36cc8b606f3b6c54688566f678e0a0722e8886/app/views/application_drafts/_action_items.haml#L2-L4) That link should go to a page containing the text of said explanation.
