### ISSUE TITLE
reason for rejection should be listed in the past applications page

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#374]
After [rejection_message](https://github.com/umts/jobapps/pull/365/files)was added, it doesn't show up anywhere after the fact. I got a complaint today that "I put a reason in the field on the application when I rejected them, but it didn’t stick."
I see no reason not to show both the note we sent them (rejection message) and the note we keep for ourselves (staff note).

**Comment by lacayodaniel** [comment]
Resolved by #379
