### ISSUE TITLE
Two interviews can be created for the same application submission

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#391]
An application submission `has_one :interview`, but there can be more than one `Interview` with the same `application_submission_id`. It's not possible in terms of workflow for one person using the app to do, however in real life there may be two separate individuals creating interviews for applicants at once.
We should save the interview in such a way that it fails to save if another interview exists with the same application submission ID. I'm sure there's an out-of-the-box Rails way of doing this. I do know that in a has_one relationship the foreign key of the previously existing object is supposed to be nullified, however `application_submission_id` is essential for interviews to exist, so perhaps this will throw the error we are looking for?

**Comment by werebus** [comment]
A very-likely related issue: the user now gets no feedback at all that the interview was scheduled. It's a [remote form](https://github.com/umts/jobapps/blob/315c6318b14f4b88b735c4934a2f5e100cbfdcbf/app/views/application_submissions/_approve.html.haml#L2) that posts to a controller action that [redirects](https://github.com/umts/jobapps/blob/315c6318b14f4b88b735c4934a2f5e100cbfdcbf/app/controllers/application_submissions_controller.rb#L65) — which doesn't do anything. If you can't remember whether you clicked the "Approve" button and you click it again, you also get this behavior.

The form was changed (probably accidentally) to a remote form in #364.

**Comment by werebus** [comment]
As far as letting the association do the work, this is actually pretty easy. If rather than do

```ruby
Interview.create(application_submission: @record, other_params)
```

you do

```ruby
@record.create_interview(other_params)
```

Then Rails destroys the existing `Interview`. Here's an example from the console with the relevent SQL queries:

```ruby
ApplicationSubmission.last.create_interview(location: 'Place', scheduled: 1.week.from_now, completed: false, hired: false, user: User.find(2))

# ApplicationSubmission Load (0.5ms)  SELECT  `application_submissions`.* FROM `application_submissions` ORDER BY `application_submissions`.`id` DESC LIMIT 1
#  (0.1ms)  BEGIN
# Interview Create (0.2ms)  INSERT INTO `interviews` (`hired`, `scheduled`, `created_at`, `updated_at`, `user_id`, `application_submission_id`, `completed`, `location`) VALUES (FALSE, '2020-08-25 21:06:09', '2020-08-18 21:06:09', '2020-08-18 21:06:09', 2, 1, FALSE, 'Place')
#  (3.6ms)  COMMIT
# Interview Load (0.4ms)  SELECT  `interviews`.* FROM `interviews` WHERE `interviews`.`application_submission_id` = 1 ORDER BY `interviews`.`scheduled` ASC LIMIT 1
#  (0.1ms)  BEGIN
# Interview Destroy (0.2ms)  DELETE FROM `interviews` WHERE `interviews`.`id` = 3
#  (3.3ms)  COMMIT
```

**Comment by Anbranin** [comment]
Oh snap, `form_with` uses remote forms unless you specify.. is it `local: true`? A fact which I had forgotten. I will change the forms so that they're local and also use your suggestion. At some point.

**Comment by Tanvish** [comment]
Should I close this issue?

**Comment by werebus** [comment]
:+1: For future reference, if your commit message contains the any of the following (case insensitive): "Close #nnn", "Closes #nnn", "Closed #nnn", "Fix #nnn", "#Fixes #nnn", or "Fixed #nnn" then Github will do that automatically.

In addition, if you forget to do that, you can choose a "Linked issue in the UI on the right.
