### ISSUE TITLE
Inform applicant

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#421]
> Would it be possible (and easy) to add a receipt to the application?  Either the applicant gets an email that says “Your application has been received”, or the page they land on after the send the application says that? 
>
> Thanks!
>
> Don

I think an email would be best because a lot of websites do that and it's very reassuring. "Your application has been received and will be processed as soon as we are able" or something. Thoughts?

**Comment by werebus** [comment]
Well, currently the page they land on already [says](https://github.com/umts/jobapps/blob/f69968748641eab9b0a80f4683b6cd5612d0da8d/app/controllers/application_submissions_controller.rb#L22-L24) "Your application has been submitted. Thank you!"

**Comment by Anbranin** [comment]
So I had assumed Don was asking because the flash message wasn't enough or something, but he was unaware it existed. He says it is sufficient.

**Comment by werebus** [comment]
Yeah, it's even "configurable". Just a quick YAML-edit:

![2021-04-26_08-36](https://user-images.githubusercontent.com/240275/116083386-8d29c080-a66a-11eb-8632-8b03b455888a.png)
