### ISSUE TITLE
Add ability to save interviews for later.

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#431]
Email from Don:

> If possible, what I would like is the ability to take an application that has had an interview, and have the option to move it from the Dashboard and save it for later without accepting, rejecting or hiring.

So, make sure the "save for later" button shows up on the interview page. This is for the case where someone has been accepted to the position after having an interview, but they won't start working or be officially "hired" until much later, later enough that you want it off the dashboard where it's cluttering things.

**Comment by Anbranin** [comment]
@jpoleary this will help close any open "view editing" training issues you have. LMK if you have questions.

**Comment by Anbranin** [comment]
I think upon further reflection it might be a big job so maybe @benmelz can help.

**Comment by werebus** [comment]
So, what is the rationale for this request? They're hired but we want to not tell them so for a long time?

**Comment by Anbranin** [comment]
Yes, that is precisely the rationale.

I'll try to condense my conversation with Don.

The reason we would want to save interviews that have already happened and not just click "hired" or "not hired" is because he doesn't actually click the "hired" button until the person 'comes back' (I think this means get their permit). This is fine, but I did ask if he needed a third column: "Accepted" was my idea. However, he stated plainly that all he wants is to be able to save interviews for later.

I think that actually adding an "accepted" button wouldn't be a bad thing (without changing EEO data, just having that be an extra attribute that moves the application to a different pile), but it requires further conversations with Don that I need to think through before having.
