### ISSUE TITLE
Inability to set an interview time

### ISSUE THREAD

**Issue by benmelz** [umts/jobapps#458]
Email report from Don:

> Good Morning,
> 
> Application number 7457 is having an issue.  When I try to set an interview time, the application gets placed in the Save for Later Review folder and I get an error message.
> 
> Thanks,
> Don

More investigation required

**Comment by dirschn** [comment]
Matt already fixed this and sent a follow up email

**Comment by benmelz** [comment]
> Matt already fixed this and sent a follow up email

Cool - I'm not sure I was CCed on said email. Might just be my mail client but to make sure what list was cced on it?

**Comment by dirschn** [comment]
`transit-it <transit-it@groups.umass.edu>`
