### ISSUE TITLE
Template drafts

### ISSUE THREAD

**Issue by dfaulken** [umts/jobapps#58]
It occurred to me yesterday that I never got around to adapting ft-forms' FormDraft system for use here. We should talk to Don about how high-priority configuring that application is for him - if it's not, then I think it'll make a good next project for @Anbranin. If it is then I'll take care of it ASAP.

**Comment by Anbranin** [comment]
Want me to ask him? I'm right here.

**Comment by dfaulken** [comment]
For posterity, Don said it wasn't a big deal and so @Anbranin worked on it (#65).
