### ISSUE TITLE
Remove or demote Codeclimate

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#610]
I'm getting a bit weary of their rubocop system that requires them to publish their own Rubocop "engine" every time there's an update. They also need to think that the same Rubocop extensions are "important" as we do.

We can keep it, maybe, but let's move linting to someplace else in the CI

**Comment by benmelz** [comment]
I don't really care for it so I vote remove - it shouldn't be an _insurmountable_ task to get our smaller apps into compliance and just all-or-nothing global lint as a ci step

**Comment by frothedoatmilk** [comment]
I don't really see why we're running rubocop on CodeClimate, at the very least. We have Travis doing the same thing, except we have much more control over how Travis works? The other checks can't hurt, although I assume we're paying for code climate...

**Comment by benmelz** [comment]
> I don't really see why we're running rubocop on CodeClimate, at the very least.

I wasn't around when it was added, but it offers an enticing set of features, namely having all your linters run and their outputs displayed prettily in one place, the ability to only enforce new offenses (more on this later), coverage drop checking and a bunch of other nebulous metrics about your code.

> We have Travis doing the same thing, except we have much more control over how Travis works? The other checks can't hurt

Travis doesn't currently run rubocop no, it strictly does the test suite. To get travis to do this and be helpful we either have to get the whole app linted as I mentioned above, or [find some way to check if we're adding _new_ offenses](https://github.com/umts/round-three/pull/6441)

>  although I assume we're paying for code climate...

We're most definitely on a free, open-source plan

**Comment by frothedoatmilk** [comment]
Throughout writing that whole message, I just realized that I mixed up rubocop and rspec. It's definitely the end of the day

**Comment by werebus** [comment]
#656
