### ISSUE TITLE
Adjust "reviewed" wording on student dashboard

### ISSUE THREAD

**Issue by benmelz** [umts/jobapps#627]
> Good Morning,
>  
> Would it be possible to make it so when an applicant completes the application and submits it, they get a confirmation on the site and are then redirected to anywhere else than the application page?  People seem to be thinking that the app failed, and they resubmit an application.
>  
> Thanks!
>  
> Don

I mean, we do send you back to the "dashboard" and there is a success message, which I'd think would be enough. Guess not though. It would be relatively inexpensive/better to send them directly to the show page application they submitted?

**Comment by werebus** [comment]
The dashboard also shows the status of their application submission(s) and interview(s). 

![Screenshot from 2024-07-22 at 12_05_32 772972113](https://github.com/user-attachments/assets/94da9b85-fc23-4193-a191-daabefe647a5)

This really feels like not an issue. Perhaps "Please select the application..." could be adjusted to say something different when there _are_ pending submissions. We could also emphasize/reword "Your application has not been reviewed yet", I guess?

**Comment by werebus** [comment]
As I thought about it, I think there's a possible point of confusion here in the two different uses of "review". Our app says that your application _hasn't_ been "reviewed" and also provides a link to "review" your application. In one case we're talking about "...by a staff memeber" and the other, we're talking about "...for your own curiosity".

**Comment by Anbranin** [comment]
I think @werebus hit the nail on the head here. With this wording it makes it seem like it's _your_ job to review your application. 
I'd change the wording to explicitly say "reviewed by staff" and use the word "view" when referring to the end user's ability to look at their application for their own curiosity.

**Comment by werebus** [comment]
Confirmed with Don that the student dashboard is already what he was looking for. So, no major changes needed.

But I think we should make the wording adjustment @Anbranin suggested.

**Comment by Anbranin** [comment]
It's been a while since I worked on jobapps, I'll take this since it's low-priority.
