### ISSUE TITLE
CSS rule that un-centers bulleted list

### ISSUE THREAD

**Issue by sherson** [umts/jobapps#63]
Looks weird, currently:
![screenshot 2015-08-11 15 11 22](https://cloud.githubusercontent.com/assets/409008/9207383/4bca9da8-403b-11e5-86c6-ebe37da5fce6.png)

**Comment by werebus** [comment]
Argh.  Lost by almost 4 minutes. :anguished:  Although mostly can be blamed on Travis, right?

**Comment by dfaulken** [comment]
http://www.burlingtonrubyconference.com/speakers/13

**Comment by sherson** [comment]
My favorite MIE professor is an expert at controls: https://mie.umass.edu/faculty/kourosh-danai
