### ISSUE TITLE
ApplicationRecord#show a little hard to read

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#66]
Currently it's a table, and that means that long questions cram answers all the way to the right of the page.  Better choices:

Truncation
-------------

Q | A
------------ | -------------
|**A very long Qu...** | Answer |

Concatenation
------------------
**Question 1**: Answer
**A longer question 2**: Answer

Alternation
--------------
**Question 1**
Answer
**Question 2**
Answer

**Comment by dfaulken** [comment]
Stylistically I think I prefer alternation. Do you have a preference?

**Comment by dfaulken** [comment]
Of the issues from today I'd prioritize this one, so I'll look into it tomorrow.

**Comment by werebus** [comment]
Don expressed a preference for concatenation, but maybe it'd be easy enough to show him both?
