### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#67]
Some staff would prefer not to have to "check another website".  Perhaps a User preference that "subscribes" to new application records in a particular department?

**Comment by dfaulken** [comment]
I'd go by position, even.

**Comment by Anbranin** [comment]
I think it'd be fun to work on this if no one else is.

**Comment by dfaulken** [comment]
Sure, go ahead!

**Comment by dfaulken** [comment]
@akaplo and @Anbranin will pair this next week.
