### ISSUE TITLE
Default interview location for positions

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#69]
Might make sense to have an attribute on positions that says where the interview typically is.

Cool thing I just leaned about:  [Plus codes](http://plus.codes/).  Try typing 87J99FV8+CJ into Google Maps.

**Comment by Anbranin** [comment]
tee hee

**Comment by dfaulken** [comment]
Right, so here's what needs to be done here:

+ [ ] An attribute on `Position` called `default_interview_location`.
+ [ ] The ability to configure this in the edit and new positions pages.
+ [ ] When scheduling an interview, the location box should default to the `default_interview_location` for the application record's position.

**Comment by dfaulken** [comment]
https://github.com/umts/jobapps/pull/85
