### ISSUE TITLE
Date and time of interview required even when staff wishes to reject application

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#76]
I wanted to see a view when the "reason for rejection" was listed, so I tried the "review application without scheduling interview" button. It told me a date and time for an interview was required. This is undesirable behavior, yes?

**Comment by werebus** [comment]
Can't reproduce.  Is there any chance you've changed something about the view locally?

**Comment by werebus** [comment]
Yup, this was a result of the view refactoring that @Anbranin was working on.
