### ISSUE TITLE
Request "Umass email" on application instead of just "email"

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#79]
Requested by Don. Even though the email address is autofilled by shibboleth, Don would prefer some extra prompting for people not to change it to another email. There was some discussion over whether this is a good idea or not. Further discussion is likely warranted.

**Comment by Anbranin** [comment]
He changed his mind.

**Comment by dfaulken** [comment]
It's not autofilled by shibboleth. It's autofilled by our users table, for people who have already submitted applications or are staff.

**Comment by werebus** [comment]
Ah.  Should it be?
