### ISSUE TITLE
In ApplicationRecord#Show, questions and answers don't line up

### ISSUE THREAD

**Issue by Anbranin** [umts/jobapps#82]
Don pointed this out to me. When someone skips a question and leaves the response blank, the next response fills its space so it looks like it's lined up with that question they skipped. If enough questions are skipped, it is nigh-unreadable. I told Don what was happening and he says he will just look at the application records very closely until we fix it.

**Comment by Anbranin** [comment]
my idea is to have them fill with a space or the word "blank" if the person leaves them blank or something. thoughts?

**Comment by werebus** [comment]
I would say that it looks to me like none of the questions are lined up.  So, my question is why in this case you went with columns and not rows.

**Comment by werebus** [comment]
Example:

![screenshot_2015-08-25_16-03-54](https://cloud.githubusercontent.com/assets/240275/9477938/eed250b0-4b42-11e5-9d81-98ae6a5a519a.png)

**Comment by dfaulken** [comment]
We reverted the branch merge which caused this problem. Don is back to having an interface which is hard to read but not inaccurate.
