### ISSUE TITLE
Access denied when directly accessingan access-controlled 

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#87]
Don reported that when he loads the jobapps site he always gets an access denied error and has to reload the page.

I determined that this happens because he has "https://transit-jobapps.admin.umass.edu/dashboard/staff" bookmarked directly.

[The order of the `before_action`s][1] is such that we *check* for spire in the session (`:set_current_user`) before *setting* spire in the session (`:set_spire`).  This isn't a problem if you load the `/` or `/dashboard/main` because those routes skip `:access_control` (running all the others) and then redirect making the order of the before hooks irrelevant.

[1]: https://github.com/umts/jobapps/blob/76205e4c0fd2e8888a203fabbeb4ce37a9da9440/app/controllers/application_controller.rb#L8-L11

**Comment by dfaulken** [comment]
Good point, nice catch. Controller TDD would be the best way to fix this.
